# HonorMC Baslatici ayarlari
jar=cekirdek/Honor-*.jar
calismaDizini=.
java=java
minRam=1G
maxRam=4G
profil=varsayilan
nogui=true
log.bilgi=true
log.uyari=true
log.hata=true
log.oyuncu=true
log.eklenti=true
jvmEkleri=
sunucuEkleri=
