# HonorMC Baslatici ayarlari
jar=cekirdek/Honor-*.jar
calismaDizini=.
java=java
minRam=1G
maxRam=4G
profil=varsayilan
nogui=true
log.bilgi=true
log.uyari=true
log.hata=true
log.oyuncu=true
log.eklenti=true
log.html=true
log.htmlDosyasi=kayitlar/canli-konsol.html
jvmEkleri=
sunucuEkleri=--config ayarlar/sunucu.properties --plugins eklentiler --world-dir dunyalar --world ana-dunya --bukkit-settings ayarlar/bukkit-uyumluluk.yml --spigot-settings ayarlar/spigot-uyumluluk.yml --paper-settings-directory ayarlar/paper --paper-settings ayarlar/paper-eski-uyumluluk.yml --purpur-settings ayarlar/purpur-uyumluluk.yml --commands-settings ayarlar/komutlar.yml
